Expand embedded linker discovery and improve error messages. (#7575)
This path didn't _quite_ work out of the box for development builds. This expands the search space to make automatic discovery more likely.

The LLVM backend's embedded linker requires `lld` to be discoverable and we make an attempt to build it from source:
https://github.com/google/iree/blob/e359a3786882b89a5d9bae7fda58ffb2384b5c87/iree/tools/CMakeLists.txt#L395-L401

However, the `lld` binary ends up in `iree-build\third_party\llvm-project\llvm\bin` for builds (`install` does put `lld` next to the other IREE tools). This now searches that path in the build tree and includes more information in error messages:
```
Searching environment for one of these tools: [iree-lld.exe, lld.exe, ld.lld.exe, lld-link.exe]
Searching for tool at path 'D:\dev\projects\iree\..\iree-build\iree\tools'
Searching for tool at path 'D:\dev\projects\iree\..\iree-build\iree\tools/../../third_party/llvm-project/llvm/bin/'

(success)
Found tool in build tree at path "D:\dev\projects\iree-build\third_party\llvm-project\llvm\bin\lld.exe"

(failure)
error: embedded linker tool (typically `lld`) not found after searching:
  * -iree-llvm-embedded-linker-path= flag
  * IREE_LLVMAOT_EMBEDDED_LINKER_PATH environment variable
  * common locations at relative file paths
  * system PATH
Run with -debug-only=llvmaot-linker for search details
```

We do also have `iree-lld` now, but that lives in [llvm-external-projects/iree-compiler-api/python/](https://github.com/google/iree/blob/main/llvm-external-projects/iree-compiler-api/python/), not [iree/tools/](https://github.com/google/iree/tree/main/iree/tools/).

A workaround we _don't_ want to encourage is to install `lld` directly at the system level. Using the built-from-source binary has less risk of compatibility issues.