Revert "Fix missing f-string (#4150)"
This reverts commit dc2e24956213c6b3c3eb2cd1fe86d74c93b53044.

Error when running test:

```
  File "/usr/local/google/home/laurenzo/src/iree-build/bindings/python/pyiree/rt/system_api.py", line 88, in _create_default_iree_driver
    print(f"Created IREE driver {driver_name}: {driver:!r}", file=sys.stderr)
TypeError: unsupported format string passed to pyiree.rt.binding.HalDriver.__format__
```