Include cstring instead of string
To use `std::strcmp`, it's required to include `<cstring>` instead of `<string>`. Otherwise the vulkan example fails to compile with clang 9:
`iree/samples/vulkan/vulkan_inference_gui.cc:121:11: error: no member named 'strcmp' in namespace 'std'; did you mean simply 'strcmp'?`

Closes https://github.com/google/iree/pull/1020

COPYBARA_INTEGRATE_REVIEW=https://github.com/google/iree/pull/1020 from iml130:vulkan_inference_gui aafc1baee7ceabb36adba47a8e7bba1c72cc78dd
PiperOrigin-RevId: 300202036