Add javatests to bazelignore
bindings/java is already excluded as it does not build and neither does javatests. Without this you get errors when trying to `bazel build bindings/...`

```
ERROR: /usr/local/google/home/gcmn/git/iree-fork/bindings/javatests/com/google/iree/BUILD:20:1: no such package 'third_party/java/junit': Package is considere
d deleted due to --deleted_packages and referenced by '//bindings/javatests/com/google/iree:ContextTest'
```

Closes https://github.com/google/iree/pull/1891

COPYBARA_INTEGRATE_REVIEW=https://github.com/google/iree/pull/1891 from GMNGeoffrey:javatests-bazelignore 221924589423e263a603d32fba83c93836c6bc54
PiperOrigin-RevId: 311208380